### PR TITLE
[concept] add async mode

### PR DESCRIPTION
**Pull request by HiFiPhile**
Add an asynchronous mode to let the Websocket server run in a separate thread, so the main program can continue to do other things.

And a asynchronous message queue is added, so other threads can also send message.

Maybe you'll do things differently, so feel free to close if you don't like it ;)

### CODE REVIEW

**Comment by Theldus** [comment]
Hi @HiFiPhile,
(Sorry for the delay in replying to you, I haven't managed time to look at this PR yet, but I'll do it in the next days.)

Thank you for your time writing this PR, I really appreciate it. Since this PR introduces some reasonably large changes to the code, I need some time to review and say if everything is ok, I hope you understand.

**Review by Theldus — COMMENTED** [review]
Hi @HiFiPhile, sorry for taking too long to answer you...

There are some things that I'm trying to understand in your code, if you do not mind to explain...
a) What is the wr/rd (inside msg_queue) purpose? count the number of writes and reads, if I were to say...
b) The async mode is only for message send, right? if so, when the message is actually sent?

There are also some things that I must point:
c) the example/ build is now broken, due to the minor changes in the interface
d) since now the reads are non-blocking, I've noticed that the server is using 100% of CPU inside `ws_establishconnection`, more specifically inside the while loop... I think this is highly undesirable, since few connections can exhaust all the machine resources.

and sorry if I'm asking silly questions, I'm not much familiar with async stuff... =)

**Comment by Theldus** [comment]
wsServer had several changes in recent weeks, which lead to merge conflicts with this PR. Also, I have not received feedback about my questions in the last months. Therefore, taking this into account, I will close this pull request.

However, I'm always open to new PRs, whether for this feature or other things. I hope you understand my decision.

**Comment by HiFiPhile** [comment]
Hi, I'm sorry I haven't update it. I'm not on this project at the moment. I'll come back later.

**Pull request closed without merging**
