### PR TITLE
Enhancement: Changed the shipping function to a more robust version

### PR DESCRIPTION
**Pull request by CleberPeter**
The write function if applied to an invalid or recently closed socket results in the SIGPIPE signal which, if not managed, breaks the application.
The use of the send function with the MSG_NOSIGNAL parameter always guarantees return -1.

### CODE REVIEW

**Comment by Theldus** [comment]
Hi @CleberPeter, thank you for your PR,

Yes, you're right, SIGPIPE can actually occur, but there are a few questions about this fix that I need to point out:

a) When compiled with `AFL_FUZZ`, [`ws_file()`](https://github.com/Theldus/wsServer/blob/master/src/ws.c#L1379) uses a file as input instead of sockets (so the existence of the `CLI_SOCK` macro), using a file fd with send() is an error.

To do this, we may be able to replace CLI_SOCK macro and adopt a SEND macro:
```c
#ifndef AFL_FUZZ
#define SEND(fd,buf,len) send((fd), (buf), (len), MSG_NOSIGNAL)
#else
#define SEND(fd,buf,len) write(fileno(stdout), (buf), (len))
#endif
```
instead of using send(), use SEND() everywhere.

b) I see that you have not changed all occurrences of `write()`, there are three in total: one in the handshake (not changed) and two in the sending of the frame (changed).

c) Once the idea is to move to the use of `send()`, it also makes sense to make use of `recv()`, mixing `read()` and `send()` sounds weird to me.

Anyway, the use of `send()/recv()` is very welcome, it is the only way for example to support Windows platforms, since there we can not make use of `read()/write()` in sockets. I even have a [draft branch/commit](https://github.com/Theldus/wsServer/commit/4653624949d9d467451db19fd144b934302cce5e) in this sense but I never got to merge with the master.

What are your thoughts on this?

**Comment by CleberPeter** [comment]
You're right.

I agree with the fact that all writings and readings must be migrated to the send () / recv () tuple which is implemented in
https://github.com/Theldus/wsServer/pull/17/commits/c54180deb5930b851b35e3a0fa41d32d845f4213

However, removing the `CLI_SOCK` macro does not seem to be that simple. It is still necessary to provide a fd to the user through the `onopen` callback. You commented that using `send` with a file fd is an error, why?

**Comment by Theldus** [comment]
> You're right.
> 
> I agree with the fact that all writings and readings must be migrated to the `send()/recv()` tuple which is implemented in
> [c54180d](https://github.com/Theldus/wsServer/commit/c54180deb5930b851b35e3a0fa41d32d845f4213).

Thank you for addressing the send/recv thing.

> However, removing the `CLI_SOCK` macro does not seem to be that simple. It is still necessary to provide a fd to the user through the `onopen` callback.

The sole purpose of the existence of the `CLI_SOCK` macro is to enable fuzzing when the library is compiled with the `AFL_FUZZ` flag. In this scenario, wsServer reads the packets through a file and responds to them via stdout, so `CLI_SOCK` only serves to pass stdout as parameter, instead of the file's fd (it would be a mess, right? read/write to the same file). While this works fine for read/write, it doesn't work for recv/send.

Think of `CLI_SOCK` as a small hack, so I believe my macro proposal below can completely eliminate the need for it.

> You commented that using `send` with a file fd is an error, why?

Yes, and it is, by the [POSIX specification](https://pubs.opengroup.org/onlinepubs/9699919799/functions/send.html), `send()` expects to receive a _socket fd_ not a 'generic' file descriptor. So in general we can only pass the return of an `accept()` as fd.

Note that this is also true for `recv()`, so we should actually do something like (include/ws.h):
```c
#ifndef AFL_FUZZ
#define SEND(fd,buf,len) send((fd), (buf), (len), MSG_NOSIGNAL)
#define RECV(fd,buf,len) recv((fd), (buf), (len), 0)
#else
#define SEND(fd,buf,len) write(fileno(stdout), (buf), (len))
#define RECV(fd,buf,len) read((fd), (buf), (len))
#endif
```

**Comment by CleberPeter** [comment]
I understand your argument, however in some references I found that the distinction between` send()` and `write()` lies solely and exclusively in the `flags` argument, that is, the `send()` method is equivalent to `write()` as long as `flags` are zero .

So it does not seem wrong to provide a generic file descriptor to the `send() `method. BUT I did a quick test:

```
char buff[] = "hello world\n";
send(fileno(stdout), buff, strlen(buff), MSG_NOSIGNAL);
```

And I didn’t verify the behavior I expected, so your approach seems more appropriate.

**Comment by Theldus** [comment]
> I understand your argument, however in some references I found that the distinction between` send()` and `write()` lies solely and exclusively in the `flags` argument, that is, the `send()` method is equivalent to `write()` as long as `flags` are zero .
> 
> So it does not seem wrong to provide a generic file descriptor to the `send() `method. BUT I did a quick test:
> 
> ```
> char buff[] = "hello world\n";
> send(fileno(stdout), buff, strlen(buff), MSG_NOSIGNAL);
> ```
> 
> And I didn’t verify the behavior I expected, so your approach seems more appropriate.

Me too, `send()` returns -1 (with Glibc and Musl) while using stdout as the file descriptor. Perhaps the difference addressed in send(2) manpage relates to socket fds, and not in general, however, this is not entirely clear.

[Here](https://stackoverflow.com/questions/1790750/what-is-the-difference-between-read-and-recv-and-between-send-and-write) is a discussion on StackOverflow, but the general consensus is that send/recv only works on sockets. Therefore, I believe that the ideal is to maintain the use of send/recv, at the same time that we use read/write for fuzzing.

**Comment by CleberPeter** [comment]
Compatibility implemented.

**Comment by Theldus** [comment]
@CleberPeter Thank you very much for working on all of these points, the PR is in good shape now =).

No regressions were found when running on the Autobahn.

**Pull request merged**
